name: lovecoffee
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  http: ^1.2.2
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/PeppermintTea.jpg
    - assets/images/FruitTea.jpg
    - assets/images/FloralTea.jpg
    - assets/images/GingerTea.jpg

    - assets/images/FrenchFries.jpg
    - assets/images/WaffleIceCream.jpg
    - assets/images/FrenchToast.jpg
    - assets/images/Croffle.jpg

    - assets/images/MatchaLatte.jpg
    - assets/images/IcedSaltedCaramelLatte.jpg
    - assets/images/ChaiLatte.jpg
    - assets/images/OatMilkLatte.jpg

    - assets/images/Coffee.jpeg
    - assets/images/onboarding1.jpg
    - assets/images/onboarding2.jpg
    - assets/images/onboarding3.jpg
  fonts:
    - family: SFPRO
      fonts:
        - asset: assets/fonts/SFPROREGULAR.otf
          weight: 700

  uses-material-design: true
